version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: playgamio_web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build: ./api
    container_name: playgamio_api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./api/db:/app/db
      - ./html/games.json:/app/games.json
      - ./html/uploads:/app/uploads
    environment:
      - ADMIN_EMAIL=admin@playgamio.com
      - ADMIN_PASSWORD=Admin@2026!
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
